### ISSUE TITLE
Add leakScope true to components

### ISSUE THREAD

**Issue by bitwhiz** [canjs/can-migrate#1]
Previously `leakScope` was [`true` by default](https://v2.canjs.com/docs/can.Component.prototype.leakScope.html). In 3.0 it is [`false` by default](https://canjs.com/doc/can-component.prototype.leakScope.html). Since determining whether a Component actually takes advantage of `leakScope` is hard, setting it to true will allow v2 components to continue working after code migration.

**Comment by andrejewski** [comment]
To accomplish this, we need a codemod like [this one I just wrote up](https://astexplorer.net/#/gist/3d024d7754676bcf88bb1fd219b015cc/222bf27bda29ca2d28efed7a3561aaecf7bb8bb9); probably a little bit smarter (`can` and `Component` could be named differently on import/require).
