### ISSUE TITLE
CanJS 6.0 codemods

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-migrate#120]
Here are the codemods that need to be created in the order I would write them in

## Update imports

- [x] `import Component from "can-component";` -> `import StacheDefineElement from "can-stache-define-element";`
- [x] `import { Component } from "can";` -> `import { StacheDefineElement } from "can";`
- [x] Same for `DefineObject` and `DefineArray`

## Update how constructors are created

- [x] Components

This:
```js
Component.extend({
  tag: "foo-bar",
  ViewModel: {},
  view: ``
});
```
...becomes:
```js
class FooBar extends StacheDefineElement {
  static get define() {
    return {}; // same as ViewModel
  }
  static get view() {
    return ``; // same as view
  }
}
customElements.define("foo-bar", FooBar);
```

- [x] DefineMap

`const Foo = DefineMap.extend({ ... });` -> `class Foo extends DefineObject {}`

- [x] DefineList

`const Foo = DefineList.extend({ ... });` -> `class Foo extends DefineList {}`

## Changes for DefineObject

These changes need to be applied after `DefineMap` is converted to `DefineObject`, so these codemods should just apply to properties in the `static define` of a `DefineObject`.

### Change shorthands:

- [x] `prop: "string"` -> `prop: type.maybeConvert(String)`
- [x] `prop: "number"` -> `prop: type.maybeConvert(Number)`
- [x] `prop: "boolean"` -> `prop: type.maybeConvert(Boolean)`
- [x] `prop: "date"` -> `prop: type.maybeConvert(Date)`
- [x] `prop: "any"` -> `prop: type.Any`

### Change property definitions:

These apply to what is in the property definition object of a property like `prop: { /* this stuff here */ }`

- [x] `Type: ...` -> `type: ...`
- [x] `Default: ...` -> `default: ...`
- [x] `type: "string"` -> `type: type.maybeConvert(String)`
- [x] `type: "number"` -> `type: type.maybeConvert(Number)`
- [x] `type: "boolean"` -> `type: type.maybeConvert(Boolean)`
- [x] `type: "date"` -> `type: type.maybeConvert(Date)`
- [x] `type: "any"` -> `type: type.Any`
- [x] `serialize: false` -> `enumerable: false`
- [x] `default() { return () => { ... } }` -> `default() { ... }`
- [x] `get(lastSet, resolve) { ... }` -> `async(resolve, lastSet) { ... }`
- [x] Need to add `type` to imports

### Move functions out of `static define`

- [x] This:

```
static define = {
  foo: function() { ... }
};
```

becomes

```
static define = {

};

foo() { ... }
```

### Handle '*'

- [x] This:

```
static define = {
  "*": { ... }
};
```

becomes

```
static define = {

};

static propertyDefaults = { ... };
```

## Changes for DefineArray

These changes need to be applied after `DefineList` is converted to `DefineArray`, so these codemods should just apply to properties in the `static define` of a `DefineArray`.

Most of the changes for DefineObject will also apply to DefineArray, but this also needs to be done:

- [x] This:

```js
const List = DefineList.extend({
  "#": Item
});
```
...becomes this:
```js
class List extends DefineList {
  static get items() {
    return Item;
  }
}
```

## Other

- [x] Component `events` object becomes a control instantiated in the `connected` hook

**Comment by phillipskevin** [comment]
question for later, do we want to codemod `new DefineList([ "one", "two" ])` to `new DefineArray(...["one", "two"])`?

**Comment by Mattchewone** [comment]
Need to account for using `new DefineList` eg:
```js
const MyVM = Component.extend({
  list: {
    value () {
      return new DefineList(['initial item'])
    }
  }
}
```

**Comment by Mattchewone** [comment]
Going to need to also add the `type` import.

Once we have converted the types:
```js
import { StacheDefineElement, DefineObject, DefineArray } from "//unpkg.com/can@5/core.mjs";
class Todo extends DefineObject {
  static get define() {
    return {
      id: type.maybeConvert(Number),
      name: type.maybeConvert(String)
    };
  }
}
```

**Comment by Mattchewone** [comment]
Transform
`get(lastSet, resolve) { ... } -> async(resolve, lastSet) { ... }`
Don't transform
`get(lastSet) { ... } -> async(resolve, lastSet) { ... }`

**Comment by Mattchewone** [comment]
Check for async functions, be sure that defined async functions are moved from within static get define, into the class body.

```js
class Foo {
  static get define () {
    async myFunc () {}
  }
}
```

Should be converted into 
```js
class Foo {
  static get define () {
  }

  async myFunc () {}
}
```

**Comment by Mattchewone** [comment]
- [ ] Alphabetize StacheDefineElement within imports
- [ ] Change the `core.mjs` import to `everything.mjs` so the `type` import worked. 

`type` was added to both imports. Probably an edge case, but it only should’ve been added to the second one.
<img width="821" alt="Screen Shot 2019-07-03 at 8 57 30 AM" src="https://user-images.githubusercontent.com/4574152/60619463-a6e08080-9dd0-11e9-9ef0-690b5318ac8f.png">

Assuming `type` will be part of core in 6.x?

**Comment by phillipskevin** [comment]
> Change the core.mjs import to everything.mjs so the type import worked.

I don't think it's worth doing this right now.

Technically, if you have:

```js
import { Component, stache } from "can";
```

...the correct thing would really be

```js
import { stache } from "can";
import { StacheDefineElement, type } from "can/everything";
```

This creates edge cases and complicates the code for something we're going to change back in a matter of weeks (when we add these packages to `core` in 6.0 as mentioned).

**Comment by Mattchewone** [comment]
Handle DefineList AssignmentExpressions, handle when we have the following:
```js
Users.List = DefineList.extend('UserList', {
  '#': 'string',

  get itemCount () {
    return this.items;
  }
});

MyComponent({
  List: Users.List
});
```

Should be converted into:
```js
class UserList extends DefineArray {
  static get define() {
    return {
      '#': 'string',

      get itemCount () {
        return this.items;
      }
    };
  }
}

MyComponent({
  List: UserList
});
```

**Comment by Mattchewone** [comment]
Duplicate declarations needs to be reviewed. 

Whilst running the code-mods against the `todomvc` guides, they throw an error after converting the `StacheDefineElement`, `DefineObject` and `DefineArray` because there are instances where there is this:

```js
Todo.List = DefineList.extend( ... )

Component.extend({ tag: 'todo-list' })
```

Which get's converted into:
```js
class TodoList extends DefineArray { ... }

class TodoList extends StacheDefineElement { ... }
```
