### ISSUE TITLE
Destructure array passed to DefineArray constructor

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-migrate#124]
When converting from `DefineList` to `DefineArray`, we need to adjust how the argument is passed. This:

```js
const foo = new DefineList([ one, two, three ]);
```

...becomes:

```js
const foo = new DefineArray(...[ one, two, three ]);
```

**Comment by Mattchewone** [comment]
We won't be able to handle this usecase:
```js
import MyList from './my-list';

const foo = new MyList([1, 2, 3]);
```

**Comment by phillipskevin** [comment]
This isn't needed anymore because https://github.com/canjs/can-observable-array/pull/44 changed the `ObservableArray` API.
