### ISSUE TITLE
Seal StacheElements and ObservableObjects

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-migrate#135]
By default `can-define` is sealed.  Should we turn this on unless `seal` is set to false?

I'd personally like to keep my components sealed.

**Comment by Mattchewone** [comment]
If we are going for similarity to existing `can-define` like we are with types: `type.maybeConvert(String)`, then yes we should look to have components sealed. 

Would this be the same for `ObservableObject` and `StacheElement` ?

**Comment by phillipskevin** [comment]
Yes, @Mattchewone, both should be sealed. We'll need to double check that it works for elements, but it should.
