### ISSUE TITLE
Replace Map and List on rest-model and realtime-rest-model

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-migrate#137]
```js
const todoConnection = restModel({
    Map: Todo,
    List: TodoList,
    url: "/api/todos/{id}"
});
```

...should become:
```js
const todoConnection = restModel({
    ObjectType: Todo,
    ArrayType: TodoList,
    url: "/api/todos/{id}"
});
```

and

```js
const Todo = realtimeRestModel("/api/todos/{id}").Map;
```

...should become:
```js
const Todo = realtimeRestModel("/api/todos/{id}").ObjectType;
```

and

```js
const Todo = realtimeRestModel("/api/todos/{id}").List;
```

...should become:
```js
const Todo = realtimeRestModel("/api/todos/{id}").ArrayType;
```

**Comment by phillipskevin** [comment]
@chasenlehara can you confirm the description above is accurate?

**Comment by phillipskevin** [comment]
cc @Mattchewone

**Comment by chasenlehara** [comment]
Yes, that’s correct!

**Comment by cherifGsoul** [comment]
should the codemod cover the use cases in the description or just the one like described for `restModel`?

Because In docs `restModel` and `realtimeRestModel` have the same signature but the description above shows two different uses.

**Comment by chasenlehara** [comment]
Everything should apply to both packages. Both packages take the new options. Both packages return a connection that has the new properties.
