### ISSUE TITLE
DefineMaps with static properties converted to ObservableObject with only static properties in props

### ISSUE THREAD

**Issue by bmomberger-bitovi** [canjs/can-migrate#155]
using the `can-observable-object/observable-object` transform:

before:
```
import DefineMap from "can-define/map/";

const Singleton = DefineMap.extend("Foo", { seal: false }, {
    foo: "number",
  });

export default Singleton;
```

after:
```
import DefineMap from "can-define/map/";

class Singleton extends ObservableObject {
  static get props() {
    return { seal: false };
  }
}
export default singleton;
```

This happens with or without the name property (`"Foo"` in the before).

Expected is that the static properties on a DefineMap are applied to the class itself later, like:

```
const Foo extends ObservableObject { 
  static get props() {
    return {
      foo: "number"
    };
  }
}
Object.assign(Foo, { seal: false });
```

Since sealing doesn't happen on ObservableObject, it may be reasonable to remove "seal" from static properties and only add others.

**Comment by cherifGsoul** [comment]
`ObservableObject` is not sealed by default, removing seal could be the right fix!
