### ISSUE TITLE
Prepare can-migrate for public release

### ISSUE THREAD

**Issue by bgando** [canjs/can-migrate#17]
Goal
  - Release can-migrate-codemods
    - Write documentation for the Readme and the Canjs website to help people run the tranforms.
Context
  - can-migrate-codemods has been used to make a successful migration in the past without any unexpected issues.
  - it is recommended that they go modlet-by-modlet and supervise the changes incrementally
  - the codemods won't cover all the bases but is good enough to be released as-is
Process 
- [x] write a how-to doc so someone can use the library to start a migration
- [x] submit documentation via PR to be reviewed by Justin
- [ ] release doc on canjs website
- [ ] add supplemental info on each transformation
- [ ] repeat 2 + 3
- [ ] if time permits, add supplemental info on contraints/bugs/known issues
- [ ] repeat 2 + 3

Success looks like a README and docs on the can.js website that are accurate and easy to understand.

**Comment by bgando** [comment]
@justinbmeyer - 
1. do you want this module to be added to the can global namespace?

**Comment by justinbmeyer** [comment]
Nope. This only runs from node, there's no reason to expose it.

**Comment by bgando** [comment]
Deprecating this issue in favor of the can-migrate epic.
