### ISSUE TITLE
-t in cli not working

### ISSUE THREAD

**Issue by bethstevic** [canjs/can-migrate#29]
Tried: can-migrate -a asdf.js --t can-capitalize/replace.js
Got: 
<img width="689" alt="screen shot 2017-07-23 at 1 52 47 pm" src="https://user-images.githubusercontent.com/15334365/28501653-4d52cf8e-6fae-11e7-987c-2883dc17da3a.png">

Tried: can-migrate -a asdf.js --transform can-capitalize/replace.js
Got: 
<img width="647" alt="screen shot 2017-07-23 at 1 52 31 pm" src="https://user-images.githubusercontent.com/15334365/28501660-636acef2-6fae-11e7-8fab-cc044df4e822.png">

Writing out 'transform' works, using '-t' shortcut does not

**Comment by chasenlehara** [comment]
It looks like the `s` and `t` aliases need to be added here: https://github.com/canjs/can-migrate/blob/69e998f2638fe0a5f2baa0d107ff88acd7765fe1/bin/can-migrate.js#L54-L58

**Comment by Zekany** [comment]
Hi!
I came across this issue while looking for beginner-friendly bugs. Since you explained what exactly the problem was, I figured I'd fix it. Should I make a pull request?

**Comment by chasenlehara** [comment]
Yes please! Let us know if you need any help submitting a PR for this. 😊

**Comment by chasenlehara** [comment]
Fixed with https://github.com/canjs/can-migrate/pull/33 and released in [v0.0.3](https://github.com/canjs/can-migrate/releases/tag/v0.0.3).

**Comment by Zekany** [comment]
No problem, thanks for opportunity!
