### ISSUE TITLE
Add support for stache("...") to the colon-bindings transform

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-migrate#40]
```
stache('{{#innerMap}}<parent-export {^value}="../parentValue"/>{{/innerMap}}')
```
is updated to 
```
stache('{{#innerMap}}<parent-export vm:value:to="../parentValue"/>{{/innerMap}}')
```

but, 
```
stache("{{#innerMap}}<parent-export {^value}='../parentValue'/>{{/innerMap}}")
```

is not updated.

**Comment by chasenlehara** [comment]
I think this is the regex that needs to be updated to support double quotes: https://github.com/canjs/can-migrate/blob/4047c4158a0b92eae1f85d36711d3a2219f4bec6/src/transforms/can-stache-bindings/colon-bindings.js#L65

**Comment by phillipskevin** [comment]
@James0x57 would know for sure.

**Comment by James0x57** [comment]
Yes, this part here:
```[''`]```
should have been:
```["'`]```

I'll submit a PR
