### ISSUE TITLE
The attr-from codemod has false positives

### ISSUE THREAD

**Issue by matthewp** [canjs/can-migrate#71]
When running this codemod on donejs-chat I got this diff:

```diff
diff --git a/src/index.stache b/src/index.stache
index d1081d3..7da4817 100644
--- a/src/index.stache
+++ b/src/index.stache
@@ -3,15 +3,15 @@
     <title>{{title}}</title>
   </head>
   <body>
-    <can-import from="bootstrap/less/bootstrap.less" />
-    <can-import from="donejs-chat/styles.less" />
-    <can-import from="donejs-chat/app" export-as="viewModel" />
+    <can-import from:from:from:from:from:from='"bootstrap/less/bootstrap.less"' />
+    <can-import from='"donejs-chat/styles.less"' />
+    <can-import from='"donejs-chat/app"' export-as:from='"viewModel"' />
 
     <div class="container">
       <div class="row">
         <div class="col-sm-8 col-sm-offset-2">
           {{#eq page 'chat'}}
-            <can-import from="donejs-chat/messages/">
+            <can-import from='"donejs-chat/messages/"'>
               {{#if isPending}}
                 Loading...
               {{else}}
@@ -19,7 +19,7 @@
               {{/if}}
             </can-import>
           {{else}}
-            <can-import from="donejs-chat/home.component">
+            <can-import from='"donejs-chat/home.component"'>
               {{#if isPending}}
                 Loading...
               {{else}}
@@ -33,10 +33,10 @@
 
     {{#switch env.NODE_ENV}}
       {{#case "production"}}
-        <script src="{{joinBase 'steal.production.js'}}"></script>
+        <script src:from:from=""{{joinBase 'steal.production.js'}}""></script>
       {{/case}}
       {{#default}}
-        <script src="/node_modules/steal/steal.js"></script>
+        <script src='"/node_modules/steal/steal.js"'></script>
       {{/default}}
     {{/switch}}
 </html>
```

I think this codemod is too eager to convert. Currently it uses a [global attribute table](https://github.com/canjs/can-migrate/blob/70f25dd3be052121cf84fba198de47e4de6deffe/lib/transforms/version-4/can-stache/attr-from.js#L8) to know what attributes shouldn't be converted.

I think instead of doing it this way it should only convert attributes that are part of elements that are valid custom elements (contain a `-` in the name), and then excluding `can-` ones because `can-import`'s attributes are not bindings.

**Comment by phillipskevin** [comment]
I think I'm going to implement your suggestion, @matthewp, but I'm still going to skip attributes that are in the `globalAttributes` list. 

I don't want to convert these attributes since people add them to custom elements for accessibility purposes.

Let me know if you see any problem with this.

**Comment by matthewp** [comment]
sounds fine

**Comment by phillipskevin** [comment]
This is still breaking in weird ways when you have certain combinations of elements. Going to take another attempt at a fix.

**Comment by phillipskevin** [comment]
Thanks for sharing your project, @MarcGodard.

I think most of the issues are problems on our end. I've opened several issues:
- [ ] https://github.com/canjs/can-migrate/issues/82
- [ ] https://github.com/donejs/donejs/issues/1091
- [ ] https://github.com/canjs/can-migrate/issues/83
- [ ] https://github.com/canjs/can-migrate/issues/84

I'll leave this open for now to track all of these.

**Comment by phillipskevin** [comment]
@MarcGodard All of these issues have been ironed out now. Give `donejs upgrade` another try when you get a chance. Let us know if you run into any other issues.

**Comment by MarcGodard** [comment]
Much better @phillipskevin, the only thing I noticed wrong was a missed change or two.

```
  days: {
    values: '00'
  },
```

was not changed.

**Comment by phillipskevin** [comment]
@MarcGodard is that just a typo? Should be `value` probably.

For the `can-globals` issue, you will probably need to go through the [migration guide](https://canjs.com/doc/migrate-4.html). Especially the "Replacements for can-event" section. Once you figure out the issue, we can figure out if it is something we can codemod.

**Comment by MarcGodard** [comment]
@phillipskevin you are right, that was a typo.

I will go through the migration guide, thanks.
