### ISSUE TITLE
Create CodeMod for Lack of Implicit Scope Walking

### ISSUE THREAD

**Issue by Sinjhin** [canjs/can-migrate#72]
can-view-scope no longer does implicit scope walking.

For instance you would need to change `{{foo}}` to `{{../foo}}` in order to find `foo` on the parent scope.

This would be very difficult to do with a codemod but we also have `{{scope.find('foo')}}` so a codemod could be made to simply wrap all scope lookups in stache with the scope.find function.

**Comment by phillipskevin** [comment]
I don't think there is a way to do this in a way that would produce code that works and is performant. People should just follow the warnings to update their scope lookups themselves.
