### ISSUE TITLE
Fix unintentional value => default transform

### ISSUE THREAD

**Issue by chasenlehara** [canjs/can-migrate#77]
Reported by @eben-roux on the forums: https://forums.donejs.com/t/using-codemods-3-4/806/7

> The original `value` in the `get` method really should not have changed.

![](https://discourse-cdn-sjc2.com/standard16/uploads/donejs/original/1X/b4275f448dcfdb6099797e5a1aa232527bcc6c38.png)

**Comment by phillipskevin** [comment]
I verified this was actually fixed already in https://github.com/canjs/can-migrate/commit/25f582b3f453db714706400f401e98276a95b31d.
