### ISSUE TITLE
Don't check in generated files

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-migrate#96]
We should only check in source files so that I can remember which one of these I’m supposed to edit:
https://github.com/canjs/can-migrate/blob/master/src/templates/can-stache/attr-from.js
https://github.com/canjs/can-migrate/blob/master/src/transforms/version-4/can-stache/attr-from.js
https://github.com/canjs/can-migrate/blob/master/lib/transforms/version-4/can-stache/attr-from.js

**Comment by Mattchewone** [comment]
This looks to have been fixed already - https://github.com/canjs/can-migrate/commit/3a5079b13f3c5c82bac509f54887c63830afb72b
